import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nabvar from "@/components/Nabvar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const locale = params.lang || "en";

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Nabvar />
        <main>{children}</main>
      </body>
    </html>
  );
}
